Remove invalid flag from doctl command
do-community/example-doctl-action pull request #15
Opened 2022-04-28 18:11 UTC by danieltharp

doctl no longer offers the --expiry-seconds flag for registry login and this will cause builds using this template to fail.

```
$ doctl registry login --expiry-seconds 600
Error: unknown flag: --expiry-seconds
Usage:
unknown flag: --expiry-seconds
  doctl registry login [flags]

Flags:
  -h, --help   help for login

Global Flags:
  -t, --access-token string   API V2 access token
  -u, --api-url string        Override default API endpoint
  -c, --config string         Specify a custom config file (default "/home/runner/.config/doctl/config.yaml")
      --context string        Specify a custom authentication context name
  -o, --output string         Desired output format [text|json] (default "text")
      --trace                 Show a log of network activity while performing a command
  -v, --verbose               Enable verbose output

Error: Process completed with exit code 255.
```

2022-04-28 19:24 UTC, andrewsomething requested changes
Hi @danieltharp,

Do you know what version of doctl you have installed?  The `--expiry-seconds` should still be supported.

```
$ doctl version
doctl version 1.73.1-release
Git commit hash: e640a1f2
$ doctl registry login --help | grep expiry
      --expiry-seconds int   The length of time the registry credentials will be valid for in seconds. By default, the credentials do not expire.
```

2022-04-28 21:53 UTC, danieltharp commented
I'm honestly not sure, I'm using whatever version is called by the `digitalocean/action-doctl@v2` step.

2022-04-29 19:05 UTC, andrewsomething commented
The flag is definitely still supported. By default, the latest version is installed. We do have a "fallback" version that is used if the call to the GitHub API to find the current one fails for some reason. 

https://github.com/digitalocean/action-doctl/blob/29d32f07563c54f3d3847f642ed1af5806d52751/main.js#L7

Looks like we're still using a very old version here. Without more info, I'd have to guess this is what got installed in your case. I'll get that updated in the action itself.

2022-04-29 21:25 UTC, closed without merging

2022-04-30 01:37 UTC, danieltharp commented
Thanks!